begin;
-- 06/09 — le cran 2 isole : la clé « pièce absente » sur le cas, l'observable isolé sur l'instance (24 exercices ex-gab-*-c2)
update exercices_cas set probleme = 'transition.limite.absente' where exercice_id = (select id from exercices where id_import = 'ex-gab-transition-annonce-vide-c2') and probleme is null;
update exercices set observable_isole_code = 'jointure_presente', observable_isole_competence = 'structure' where id_import = 'ex-gab-transition-annonce-vide-c2' and observable_isole_code is null;
update exercices_cas set probleme = 'transition.limite.absente' where exercice_id = (select id from exercices where id_import = 'ex-gab-transition-bilan-absent-c2') and probleme is null;
update exercices set observable_isole_code = 'jointure_presente', observable_isole_competence = 'structure' where id_import = 'ex-gab-transition-bilan-absent-c2' and observable_isole_code is null;
update exercices_cas set probleme = 'transition.limite.absente' where exercice_id = (select id from exercices where id_import = 'ex-gab-transition-bilan-infidele-c2') and probleme is null;
update exercices set observable_isole_code = 'jointure_presente', observable_isole_competence = 'structure' where id_import = 'ex-gab-transition-bilan-infidele-c2' and observable_isole_code is null;
update exercices_cas set probleme = 'transition.limite.absente' where exercice_id = (select id from exercices where id_import = 'ex-gab-transition-limite-absente-c2') and probleme is null;
update exercices set observable_isole_code = 'jointure_presente', observable_isole_competence = 'structure' where id_import = 'ex-gab-transition-limite-absente-c2' and observable_isole_code is null;
update exercices_cas set probleme = 'transition.limite.absente' where exercice_id = (select id from exercices where id_import = 'ex-gab-transition-limite-declaree-c2') and probleme is null;
update exercices set observable_isole_code = 'jointure_presente', observable_isole_competence = 'structure' where id_import = 'ex-gab-transition-limite-declaree-c2' and observable_isole_code is null;
update exercices_cas set probleme = 'transition.limite.absente' where exercice_id = (select id from exercices where id_import = 'ex-gab-transition-limite-formule-c2') and probleme is null;
update exercices set observable_isole_code = 'jointure_presente', observable_isole_competence = 'structure' where id_import = 'ex-gab-transition-limite-formule-c2' and observable_isole_code is null;
update exercices_cas set probleme = 'transition.limite.absente' where exercice_id = (select id from exercices where id_import = 'ex-gab-transition-limite-mal-dirigee-c2') and probleme is null;
update exercices set observable_isole_code = 'jointure_presente', observable_isole_competence = 'structure' where id_import = 'ex-gab-transition-limite-mal-dirigee-c2' and observable_isole_code is null;
update exercices_cas set probleme = 'argument.garant.absent' where exercice_id = (select id from exercices where id_import = 'ex-gab-argument-garant-circulaire-c2') and probleme is null;
update exercices set observable_isole_code = 'lien_explicite', observable_isole_competence = 'argumentation' where id_import = 'ex-gab-argument-garant-circulaire-c2' and observable_isole_code is null;
update exercices_cas set probleme = 'argument.garant.absent' where exercice_id = (select id from exercices where id_import = 'ex-gab-argument-garant-connecteur-c2') and probleme is null;
update exercices set observable_isole_code = 'lien_explicite', observable_isole_competence = 'argumentation' where id_import = 'ex-gab-argument-garant-connecteur-c2' and observable_isole_code is null;
update exercices_cas set probleme = 'argument.garant.absent' where exercice_id = (select id from exercices where id_import = 'ex-gab-argument-garant-glissant-c2') and probleme is null;
update exercices set observable_isole_code = 'lien_explicite', observable_isole_competence = 'argumentation' where id_import = 'ex-gab-argument-garant-glissant-c2' and observable_isole_code is null;
update exercices_cas set probleme = 'argument.garant.absent' where exercice_id = (select id from exercices where id_import = 'ex-gab-argument-garant-vague-c2') and probleme is null;
update exercices set observable_isole_code = 'lien_explicite', observable_isole_competence = 'argumentation' where id_import = 'ex-gab-argument-garant-vague-c2' and observable_isole_code is null;
update exercices_cas set probleme = 'argument.garant.absent' where exercice_id = (select id from exercices where id_import = 'ex-gab-argument-preuve-circulaire-c2') and probleme is null;
update exercices set observable_isole_code = 'lien_explicite', observable_isole_competence = 'argumentation' where id_import = 'ex-gab-argument-preuve-circulaire-c2' and observable_isole_code is null;
update exercices_cas set probleme = 'phrase.rattachement.absent' where exercice_id = (select id from exercices where id_import = 'ex-gab-phrase-tenue-sens-perdu-c2') and probleme is null;
update exercices set observable_isole_code = 'attache_presente', observable_isole_competence = 'expression' where id_import = 'ex-gab-phrase-tenue-sens-perdu-c2' and observable_isole_code is null;
update exercices_cas set probleme = 'objection.traitement.absent' where exercice_id = (select id from exercices where id_import = 'ex-gab-objection-accord-non-retourne-c2') and probleme is null;
update exercices set observable_isole_code = 'objection_traitee', observable_isole_competence = 'argumentation' where id_import = 'ex-gab-objection-accord-non-retourne-c2' and observable_isole_code is null;
update exercices_cas set probleme = 'objection.traitement.absent' where exercice_id = (select id from exercices where id_import = 'ex-gab-objection-maillon-general-c2') and probleme is null;
update exercices set observable_isole_code = 'objection_traitee', observable_isole_competence = 'argumentation' where id_import = 'ex-gab-objection-maillon-general-c2' and observable_isole_code is null;
update exercices_cas set probleme = 'objection.traitement.absent' where exercice_id = (select id from exercices where id_import = 'ex-gab-objection-maillon-hors-these-c2') and probleme is null;
update exercices set observable_isole_code = 'objection_traitee', observable_isole_competence = 'argumentation' where id_import = 'ex-gab-objection-maillon-hors-these-c2' and observable_isole_code is null;
update exercices_cas set probleme = 'objection.traitement.absent' where exercice_id = (select id from exercices where id_import = 'ex-gab-objection-traitement-retournement-c2') and probleme is null;
update exercices set observable_isole_code = 'objection_traitee', observable_isole_competence = 'argumentation' where id_import = 'ex-gab-objection-traitement-retournement-c2' and observable_isole_code is null;
update exercices_cas set probleme = 'paragraphe.exploitation.absente' where exercice_id = (select id from exercices where id_import = 'ex-gab-paragraphe-exploitation-connecteur-c2') and probleme is null;
update exercices set observable_isole_code = 'attache_presente', observable_isole_competence = 'expression' where id_import = 'ex-gab-paragraphe-exploitation-connecteur-c2' and observable_isole_code is null;
update exercices_cas set probleme = 'paragraphe.exploitation.absente' where exercice_id = (select id from exercices where id_import = 'ex-gab-paragraphe-exploitation-voisine-c2') and probleme is null;
update exercices set observable_isole_code = 'attache_presente', observable_isole_competence = 'expression' where id_import = 'ex-gab-paragraphe-exploitation-voisine-c2' and observable_isole_code is null;
update exercices_cas set probleme = 'paragraphe.exploitation.absente' where exercice_id = (select id from exercices where id_import = 'ex-gab-paragraphe-retour-idee-neuve-c2') and probleme is null;
update exercices set observable_isole_code = 'attache_presente', observable_isole_competence = 'expression' where id_import = 'ex-gab-paragraphe-retour-idee-neuve-c2' and observable_isole_code is null;
update exercices_cas set probleme = 'paragraphe.exploitation.absente' where exercice_id = (select id from exercices where id_import = 'ex-gab-paragraphe-retour-retractation-c2') and probleme is null;
update exercices set observable_isole_code = 'attache_presente', observable_isole_competence = 'expression' where id_import = 'ex-gab-paragraphe-retour-retractation-c2' and observable_isole_code is null;
update exercices_cas set probleme = 'exemple.exploitation.absente' where exercice_id = (select id from exercices where id_import = 'ex-gab-exemple-attache-absente-c2') and probleme is null;
update exercices set observable_isole_code = 'attache_presente', observable_isole_competence = 'expression' where id_import = 'ex-gab-exemple-attache-absente-c2' and observable_isole_code is null;
update exercices_cas set probleme = 'exemple.exploitation.absente' where exercice_id = (select id from exercices where id_import = 'ex-gab-exemple-attache-ainsi-c2') and probleme is null;
update exercices set observable_isole_code = 'attache_presente', observable_isole_competence = 'expression' where id_import = 'ex-gab-exemple-attache-ainsi-c2' and observable_isole_code is null;
update exercices_cas set probleme = 'exemple.exploitation.absente' where exercice_id = (select id from exercices where id_import = 'ex-gab-exemple-exploitation-jugement-c2') and probleme is null;
update exercices set observable_isole_code = 'attache_presente', observable_isole_competence = 'expression' where id_import = 'ex-gab-exemple-exploitation-jugement-c2' and observable_isole_code is null;
select count(*) filter (where c.probleme is not null) as cas_avec_cle, count(*) filter (where e.observable_isole_code is not null) as instances_avec_observable, count(*) as total from exercices e join exercices_cas c on c.exercice_id = e.id where e.id_import like 'ex-gab-%-c2';
commit;
